version: '3.3'

services:     
  app:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports: 
      - 80:9000      
      - 9001:9000  
    environment: 
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=ACCESS_KEY
      - AWS_SECRET_KEY=SECRET_KEY
      - REDIS_URL=redis.fcq4bj.0001.apse1.cache.amazonaws.com:6379
      - REDIS_TTL=2592000
      - JWT_SECRET=my_super_secret_key      
