version: '3.3'

services:   
  redis:
    image: redis:alpine
    restart: always      
    ports: 
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - default
  
  app:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports: 
      - 9001:9000
      - 9002:9000
    depends_on: 
      - redis
    networks:
      - default
    environment: 
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAQFG3MA563D6YLGUF
      - AWS_SECRET_KEY=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
      - REDIS_URL=redis:6379
      - REDIS_TTL=10
      - JWT_SECRET=my_super_secret_key

volumes:
  redis-data:      

networks:
  default: